-- MySQL Script generated by MySQL Workbench
-- Sun Mar 29 16:15:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Warehouse` (
  `WarehouseID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `ContactPhone` VARCHAR(45) NULL,
  `ContactEmail` VARCHAR(45) NULL,
  `ContactEmployeeID` VARCHAR(45) NULL,
  PRIMARY KEY (`WarehouseID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `CustomerID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Store` (
  `StoreID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `ContactPhone` VARCHAR(45) NULL,
  `ContactEmail` VARCHAR(45) NULL,
  `ContactEmployeeID` VARCHAR(45) NULL,
  PRIMARY KEY (`StoreID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CustomerOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CustomerOrder` (
  `CustomerOrderID` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  `StoreID` INT NOT NULL,
  `DateOfOrder` DATETIME NULL,
  `DateOfPickup` DATETIME NULL,
  `CustomerPayment` DECIMAL NULL,
  PRIMARY KEY (`CustomerOrderID`, `CustomerID`, `StoreID`),
  INDEX `fk_CustomereOrder_Customer_idx` (`CustomerID` ASC) VISIBLE,
  INDEX `fk_CustomerOrder_Store_idx` (`StoreID` ASC) VISIBLE,
  CONSTRAINT `fk_CustomerOrder_Customer`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CustomerOrder_Store`
    FOREIGN KEY (`StoreID`)
    REFERENCES `mydb`.`Store` (`StoreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `EmployeeID` INT NOT NULL,
  `StoreID` INT NULL,
  `WarehouseID` INT NULL,
  `Name` LONGTEXT NOT NULL,
  `EmployeeType` INT NOT NULL,
  `Phone` INT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Adress` LONGTEXT NULL,
  `ManagerID` INT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EmployeeID`),
  INDEX `fk_Employee_Warehouse_idx` (`WarehouseID` ASC) INVISIBLE,
  INDEX `fk_Employee_Store1_idx` (`StoreID` ASC) VISIBLE,
  INDEX `fk_Empoloyee_Empoloyee_idx` (`ManagerID` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Warehouse`
    FOREIGN KEY (`WarehouseID`)
    REFERENCES `mydb`.`Warehouse` (`WarehouseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Store`
    FOREIGN KEY (`StoreID`)
    REFERENCES `mydb`.`Store` (`StoreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empoloyee_Empoloyee`
    FOREIGN KEY (`ManagerID`)
    REFERENCES `mydb`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InventoryOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`InventoryOrder` (
  `InventoryOrderID` INT NOT NULL,
  `EmployeeID` INT NOT NULL,
  `StoreID` INT NOT NULL,
  `WarehouseID` INT NOT NULL,
  `DateOfOrder` INT NULL,
  `DeliveryDate` INT NULL,
  `ManagerApporval` TINYINT NULL,
  INDEX `fk_Order_Store_idx` (`StoreID` ASC) VISIBLE,
  INDEX `fk_Order_Warehouse_idx` (`WarehouseID` ASC) VISIBLE,
  PRIMARY KEY (`InventoryOrderID`, `EmployeeID`, `StoreID`, `WarehouseID`),
  INDEX `fk_InventoryOrder_Employee_idx` (`EmployeeID` ASC) VISIBLE,
  CONSTRAINT `fk_InventoryOrder_Store`
    FOREIGN KEY (`StoreID`)
    REFERENCES `mydb`.`Store` (`StoreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InventoryOrder_Warehouse`
    FOREIGN KEY (`WarehouseID`)
    REFERENCES `mydb`.`Warehouse` (`WarehouseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InventoryOrder_Employee`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `mydb`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `ProductID` INT NOT NULL,
  `Name` LONGTEXT NULL,
  `Barcode` LONGTEXT NULL,
  `Description` LONGTEXT NULL,
  `Price` DECIMAL NULL,
  `Weight` INT NULL,
  PRIMARY KEY (`ProductID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CustomerOrderProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CustomerOrderProduct` (
  `CustomerOrderProductID` INT NOT NULL,
  `CustomerOrderID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  `OrderQuantity` INT NULL,
  PRIMARY KEY (`CustomerOrderProductID`, `CustomerOrderID`, `ProductID`),
  INDEX `fk_CustomerOrderProduct_Product_idx` (`ProductID` ASC) VISIBLE,
  INDEX `fk_CustomerOrderProduct_CustomerOrder_idx` (`CustomerOrderID` ASC) VISIBLE,
  CONSTRAINT `fk_CustomerOrderProduct_Product`
    FOREIGN KEY (`ProductID`)
    REFERENCES `mydb`.`Products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CustomerOrderProduct_CustomerOrder`
    FOREIGN KEY (`CustomerOrderID`)
    REFERENCES `mydb`.`CustomerOrder` (`CustomerOrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InventoryOrderProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`InventoryOrderProduct` (
  `InventoryOrderProductID` INT NOT NULL,
  `InventoryOrderID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  `OrderQuantity` INT NULL,
  PRIMARY KEY (`InventoryOrderProductID`, `InventoryOrderID`, `ProductID`),
  INDEX `fk_InventoryOrderProduct_InventoryOrder_idx` (`InventoryOrderID` ASC) VISIBLE,
  INDEX `fk_OrderProduct_Product_idx` (`ProductID` ASC) VISIBLE,
  CONSTRAINT `fk_InventoryOrderProduct_InventoryOrder`
    FOREIGN KEY (`InventoryOrderID`)
    REFERENCES `mydb`.`InventoryOrder` (`InventoryOrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InventoryOrderProduct_Product`
    FOREIGN KEY (`ProductID`)
    REFERENCES `mydb`.`Products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WarehouseProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WarehouseProduct` (
  `WarehouseProductID` INT NOT NULL,
  `WarehouseID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  `CountOnHand` INT NULL,
  PRIMARY KEY (`WarehouseProductID`, `WarehouseID`, `ProductID`),
  INDEX `fk_WarehouseProduct_Warehouse_idx` (`WarehouseID` ASC) VISIBLE,
  INDEX `fk_WarehouseProduct_Product_idx` (`ProductID` ASC) VISIBLE,
  CONSTRAINT `fk_WarehouseProduct_Warehouse`
    FOREIGN KEY (`WarehouseID`)
    REFERENCES `mydb`.`Warehouse` (`WarehouseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WarehouseProduct_Product`
    FOREIGN KEY (`ProductID`)
    REFERENCES `mydb`.`Products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StoreProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StoreProduct` (
  `StoreProductID` INT NOT NULL,
  `StoreID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  `CountOnHand` INT NULL,
  PRIMARY KEY (`StoreProductID`, `StoreID`, `ProductID`),
  INDEX `fk_StoreProduct_Product_idx` (`ProductID` ASC) VISIBLE,
  INDEX `fk_StoreProduct_Store_idx` (`StoreID` ASC) VISIBLE,
  CONSTRAINT `fk_StoreProduct_Product`
    FOREIGN KEY (`ProductID`)
    REFERENCES `mydb`.`Products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StoreProduct_Store`
    FOREIGN KEY (`StoreID`)
    REFERENCES `mydb`.`Store` (`StoreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
